site_name: LLM Training Hub Documentation
site_description: A technical reference for training techniques for LLMs.
site_author: Saurabh Goyal
repo_url: https://github.com/saurabhiit2007/LLM-Training-Hub
theme:
  name: material
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - mathjax
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep purple
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
  font:
    text: Inter
    code: JetBrains Mono

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Training Phases:
      - Pre-Training: ./training_phases/pre_training.md
      - Mid-Training: ./training_phases/mid_training.md
      - Post-Training (SFT): ./training_phases/post_training.md
  - Distributed Training:
      - Parallelism Overview: ./distributed_training/parallelism_overview.md
      - Data Parallelism: ./distributed_training/data_parallelism.md
      - Tensor Parallelism: ./distributed_training/tensor_parallelism.md
      - Pipeline Parallelism: ./distributed_training/pipeline_parallelism.md
      - Zero-Deepspeed: ./distributed_training/zero_deepspeed.md
      - FSDP: ./distributed_training/fsdp.md
  - PEFT Techniques:
      - LoRA: ./parameter_efficient_fine_tuning/lora.md
      - QLoRA: ./parameter_efficient_fine_tuning/qlora.md
      - Adaptors: ./parameter_efficient_fine_tuning/adaptors.md
      - 4-bit NormalFloat (NF4): ./parameter_efficient_fine_tuning/4bit_normal_float.md
      - Block-wise k-bit Quantization: ./parameter_efficient_fine_tuning/blockwise_kbit_quantization.md
  - Optimization:
      - Mixed Precision: ./optimization/mixed_precision.md
      - Gradient Checkpointing: ./optimization/gradient_checkpointing.md
      - Memory Efficient Optimizers: ./optimization/memory_efficient_optimizers.md
      - Optimizers-Schedules: ./optimization/optimizers_schedules.md
      - Quantization: ./optimization/quantization.md
      - Memory Considerations: ./optimization/memory_considerations.md
  - Frameworks:
      - Accelerate Framework: ./frameworks/accelerate.md
  - References: references.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes
  - tables
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.magiclink
